# Generated by Django 5.1.5 on 2025-01-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='historicalcommande',
            old_name='created_at',
            new_name='date',
        ),
    ]
