# Generated by Django 5.1.5 on 2025-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_rename_created_at_commande_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='classe',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'double jaune'), (3, 'blanc'), (4, 'sale'), (5, 'casse'), (6, 'elimine'), (7, 'triage')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcommande',
            name='classe',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'double jaune'), (3, 'blanc'), (4, 'sale'), (5, 'casse'), (6, 'elimine'), (7, 'triage')], default=1),
        ),
    ]
