# Generated by Django 5.1.5 on 2025-01-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementtry',
            name='paiement_by_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tries', to='paiements.paiementbyclient'),
        ),
        migrations.AlterField(
            model_name='paiementtry',
            name='paiement_by_command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tries', to='paiements.paiementbycommand'),
        ),
        migrations.AlterField(
            model_name='paiementtry',
            name='paiement_direct_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tries', to='paiements.paimentbydirectsale'),
        ),
    ]
