# Generated by Django 5.1.5 on 2025-01-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('paiements', '0003_historicalpaiementtry_status_paiementtry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaiementtry',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.client'),
        ),
        migrations.AddField(
            model_name='paiementtry',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.client'),
        ),
    ]
