# Generated by Django 5.1.5 on 2025-02-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_historicalpaiementtry_client_paiementtry_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaiementbycommand',
            old_name='commade',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='paiementbycommand',
            old_name='commade',
            new_name='commande',
        ),
    ]
