# Generated by Django 5.1.5 on 2025-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_rename_commade_historicalpaiementbycommand_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaiementtry',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paiementtry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
