# Generated by Django 5.1.5 on 2025-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduction',
            name='tare_alveole',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='production',
            name='tare_alveole',
            field=models.FloatField(default=70),
        ),
    ]
