# Generated by Django 5.1.5 on 2025-02-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventaire',
            old_name='is_plus',
            new_name='is_positive',
        ),
    ]
