# Generated by Django 5.1.5 on 2025-01-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcharge',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
