# Generated by Django 5.1.5 on 2025-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_charge_quantity_historicalcharge_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='classe',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'double jaune'), (3, 'blanc'), (4, 'sale'), (5, 'casse'), (6, 'elimine'), (7, 'triage')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcharge',
            name='classe',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'double jaune'), (3, 'blanc'), (4, 'sale'), (5, 'casse'), (6, 'elimine'), (7, 'triage')], default=1),
        ),
    ]
